# Use an official Node.js runtime as the base image
FROM node:14-alpine AS build

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package*.json ./

# Install the app dependencies
RUN npm install

# Copy the app source code
COPY . .

# Build the React app for production
RUN npm run build

# Use a lightweight web server to serve the production build
FROM nginx:alpine

# Copy the built React app from the build stage to the NGINX HTML folder
COPY --from=build /app/build /usr/share/nginx/html

# Expose the port that NGINX will run on
EXPOSE 80

# Start NGINX server
CMD ["nginx", "-g", "daemon off;"]
